name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"  # Adjust size based on needs
      API_URL: ${{ vars.TEST_API_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_AUTH_GITHUB_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_GITHUB_CLIENT_ID }}
      SUPABASE_AUTH_GITHUB_SECRET: ${{ secrets.SUPABASE_AUTH_GITHUB_SECRET }}
      SUPABASE_AUTH_GOOGLE_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_GOOGLE_CLIENT_ID }}
      SUPABASE_AUTH_GOOGLE_SECRET: ${{ secrets.SUPABASE_AUTH_GOOGLE_SECRET }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      NEXT_PUBLIC_NODE_ENV: testing

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Copy test env vars
        run: cp .env.example .env
      - name: Prepare environment
        uses: ./.github/actions/prepare-env
        with:
          NODE_OPTIONS: "--max-old-space-size=4096"  # Adjust size based on needs
          API_URL: ${{ vars.TEST_API_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_AUTH_GITHUB_CLIENT_ID:  ${{ secrets.SUPABASE_AUTH_GITHUB_CLIENT_ID }}
          SUPABASE_AUTH_GITHUB_SECRET:  ${{ secrets.SUPABASE_AUTH_GITHUB_SECRET }}
          SUPABASE_AUTH_GOOGLE_CLIENT_ID:  ${{ secrets.SUPABASE_AUTH_GOOGLE_CLIENT_ID }}
          SUPABASE_AUTH_GOOGLE_SECRET:  ${{ secrets.SUPABASE_AUTH_GOOGLE_SECRET }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_NODE_ENV: testing
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm db:migrate
      - run: pnpm db:seed
