name: Test NestJS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  pull_request:
    branches: [staging]

# A workflow for testing NestJS
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"  # Adjust size based on needs
      API_URL: ${{ vars.TEST_API_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_AUTH_GITHUB_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_GITHUB_CLIENT_ID }}
      SUPABASE_AUTH_GITHUB_SECRET: ${{ secrets.SUPABASE_AUTH_GITHUB_SECRET }}
      SUPABASE_AUTH_GOOGLE_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_GOOGLE_CLIENT_ID }}
      SUPABASE_AUTH_GOOGLE_SECRET: ${{ secrets.SUPABASE_AUTH_GOOGLE_SECRET }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Copy test env vars
        run: cp .env.example .env
      - name: Prepare environment
        uses: ./.github/actions/prepare-env
        with:
          NODE_OPTIONS: "--max-old-space-size=4096"  # Adjust size based on needs
          API_URL: ${{ vars.TEST_API_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_AUTH_GITHUB_CLIENT_ID:  ${{ secrets.SUPABASE_AUTH_GITHUB_CLIENT_ID }}
          SUPABASE_AUTH_GITHUB_SECRET:  ${{ secrets.SUPABASE_AUTH_GITHUB_SECRET }}
          SUPABASE_AUTH_GOOGLE_CLIENT_ID:  ${{ secrets.SUPABASE_AUTH_GOOGLE_CLIENT_ID }}
          SUPABASE_AUTH_GOOGLE_SECRET:  ${{ secrets.SUPABASE_AUTH_GOOGLE_SECRET }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_NODE_ENV: "testing"
      - name: Build
        run: pnpm build
        shell: bash
      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: pnpm start -p 3000
          wait-on: 'http://localhost:3000'
          working-directory: .
      - name: Run cypress component tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          component: true
          install: false
          working-directory: .